repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.json # Tránh quét các file manifest có mã hash ngẫu nhiên nhưng vô hại

  # Cho Mobile (Flutter)
  - repo: local
    hooks:
      - id: flutter-format
        name: Flutter Format
        entry: flutter format .
        language: system
        files: \.dart$
        pass_filenames: false

  # Cho AI Agent (Python)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: ^petties-agent-serivce/

  # Cho Frontend (React)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^petties-web/.*\.(js|jsx|ts|tsx)$
        args: ["--fix"]
